from .node import NODE_CLASS_MAPPINGS as PF_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PF_NAMES
from .lora_forge import NODE_CLASS_MAPPINGS as LF_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LF_NAMES

NODE_CLASS_MAPPINGS = {**PF_MAPPINGS, **LF_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**PF_NAMES, **LF_NAMES}

WEB_DIRECTORY = "./js"

print(f"[PromptForgeLD] v2 overhaul loaded — {list(NODE_DISPLAY_NAME_MAPPINGS.values())}")

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
